# -*- coding: utf-8 -*-
"""proyectofinanzas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NbeqBzZNOPH1wNYjTvede_kzJWgA8MZi

# 📊 Alpha Vantage API - Análisis Financiero Completo
## Cuaderno interactivo para Google Colab

**Autor:** Asistente de IA  
**Fecha:** 2026  

Este cuaderno explora todas las funcionalidades de la API Alpha Vantage incluyendo:
- 📈 Datos de acciones (diarios, semanales, mensuales, intradía)
- ₿ Criptomonedas
- 📉 Indicadores técnicos
-  Commodities (oro, petróleo, etc.)
- 📊 Visualizaciones interactivas

## 📋 Tabla de Contenidos
1. [Configuración Inicial](#configuracion)
2. [Instalación de Librerías](#instalacion)
3. [Configuración de API Key](#apikey)
4. [Datos de Acciones](#acciones)
   - Time Series Intradiario
   - Time Series Diario
   - Time Series Semanal y Mensual
5. [Criptomonedas](#crypto)
6. [Indicadores Técnicos](#tecnicos)
7. [Commodities](#commodities)
8. [Análisis y Visualizaciones](#analisis)

## 1. Configuración Inicial <a id='configuracion'></a>
"""

# Verificar que estamos en Google Colab
import sys
if 'google.colab' in sys.modules:
    print("✅ Ejecutando en Google Colab")
else:
    print("️ No estás en Google Colab, pero el cuaderno debería funcionar")

"""## 2. Instalación de Librerías <a id='instalacion'></a>"""

# Instalar librerías necesarias
!pip install requests pandas matplotlib plotly seaborn -q

print("✅ Librerías instaladas correctamente")

# Importar todas las librerías necesarias
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Configurar estilo de visualizaciones
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

print("✅ Librerías importadas correctamente")

"""## 3. Configuración de API Key <a id='apikey'></a>"""

# ============================================
# 📝 COLOCA TU API KEY DE ALPHA VANTAGE AQUÍ
# ============================================
# Obtén tu API key gratuita en: https://www.alphavantage.co/support/#api-key
API_KEY = '45CRE0CEN8FEAW6B'
BASE_URL = 'https://www.alphavantage.co/query'

# Verificar que la API key fue configurada
if API_KEY == '45CRE0CEN8FEAW6B':
    print("⚠️ ADVERTENCIA: Debes reemplazar 'TU_API_KEY_AQUI' con tu API key real")
    print(" Obtén tu API key gratuita en: https://www.alphavantage.co/support/#api-key")
else:
    print("✅ API Key configurada correctamente")
    print(f" API Key: {API_KEY[:10]}...{API_KEY[-4:]}")

"""## 4. Funciones Helper para la API"""

def hacer_request(params):
    """
    Función helper para hacer requests a la API de Alpha Vantage

    Args:
        params: Diccionario con los parámetros de la API

    Returns:
        JSON response de la API
    """
    params['apikey'] = API_KEY
    try:
        response = requests.get(BASE_URL, params=params)
        data = response.json()

        # Verificar si hay un mensaje de error
        if 'Error Message' in data:
            print(f"❌ Error: {data['Error Message']}")
            return None
        elif 'Note' in data:
            print(f"⚠️ Nota: {data['Note']}")
            return None
        elif 'Information' in data: # Manejar mensajes de límite de API gratuita / característica premium
            print(f"⚠️ Información/Límite API: {data['Information']}")
            return None

        return data
    except Exception as e:
        print(f"❌ Error en la request: {e}")
        return None

def convertir_a_dataframe(data, time_series_key):
    """
    Convierte los datos de la API en un DataFrame de pandas
    (Para Time Series que usan una clave de series de tiempo)

    Args:
        data: JSON response de la API
        time_series_key: La clave del time series en el JSON

    Returns:
        DataFrame con los datos
    """
    if data is None:
        return None

    # Check if the time_series_key exists, otherwise return None
    if time_series_key not in data:
        print(f"❌ Error: La clave '{time_series_key}' no se encontró en los datos.")
        return None

    df = pd.DataFrame.from_dict(data[time_series_key], orient='index')
    df.index = pd.to_datetime(df.index)
    df = df.astype(float)
    return df.sort_index(ascending=False)

def convertir_commodities_a_dataframe(data):
    """
    Convierte los datos de commodities de la API (lista de diccionarios) en un DataFrame de pandas

    Args:
        data: JSON response de la API para commodities (e.g., GOLD_SILVER_HISTORY, WTI)

    Returns:
        DataFrame con los datos
    """
    if data is None or 'data' not in data:
        print("❌ Error: Datos de commodities incompletos o nulos.")
        return None

    df = pd.DataFrame(data['data'])
    df['date'] = pd.to_datetime(df['date'])
    df = df.set_index('date')
    # Convert all other columns to float, coercing errors
    for col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')
    return df.sort_index(ascending=False)

print("✅ Funciones helper creadas correctamente")

"""## 5. Datos de Acciones <a id='acciones'></a>

### 5.1 Time Series Diario - Daily Time Series
"""

# ============================================
# 📈 TIME SERIES DIARIO
# ============================================
# Obtiene datos históricos diarios de una acción

symbol = 'IBM'  # Puedes cambiar por AAPL, GOOGL, MSFT, etc.
print(f"📊 Obteniendo datos diarios para {symbol}...")

params = {
    'function': 'TIME_SERIES_DAILY',
    'symbol': symbol,
    'outputsize': 'compact'  # 'compact' = últimos 100 días, 'full' = todos los datos
}

data_daily = hacer_request(params)

if data_daily:
    df_daily = convertir_a_dataframe(data_daily, 'Time Series (Daily)')

    # Renombrar columnas
    df_daily.columns = ['Open', 'High', 'Low', 'Close', 'Volume']

    print(f"✅ Datos obtenidos exitosamente")
    print(f"📅 Período: {df_daily.index[-1].date()} a {df_daily.index[0].date()}")
    print(f"📊 Total de registros: {len(df_daily)}")
    print("\n📋 Últimos 5 registros:")
    display(df_daily.head())

    # Guardar para visualizaciones posteriores
    df_stock = df_daily.copy()
else:
    print("❌ No se pudieron obtener los datos")
    df_stock = None

# Visualización del precio de cierre
if df_stock is not None:
    fig, axes = plt.subplots(2, 1, figsize=(14, 10))

    # Gráfico de precios
    axes[0].plot(df_stock.index, df_stock['Close'], linewidth=2, color='#2E86AB')
    axes[0].set_title(f'Precio de Cierre - {symbol}', fontsize=14, fontweight='bold')
    axes[0].set_ylabel('Precio USD ($)', fontsize=12)
    axes[0].grid(True, alpha=0.3)

    # Gráfico de volumen
    axes[1].bar(df_stock.index, df_stock['Volume'], alpha=0.6, color='#A23B72')
    axes[1].set_title('Volumen de Operaciones', fontsize=14, fontweight='bold')
    axes[1].set_ylabel('Volumen', fontsize=12)
    axes[1].set_xlabel('Fecha', fontsize=12)
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

    # Estadísticas descriptivas
    print("\n📊 Estadísticas Descriptivas - Precio de Cierre:")
    print(df_stock['Close'].describe())

"""### 5.2 Time Series Semanal - Weekly Time Series"""

# ============================================
# 📅 TIME SERIES SEMANAL
# ============================================

print(f"📊 Obteniendo datos semanales para {symbol}...")

params = {
    'function': 'TIME_SERIES_WEEKLY',
    'symbol': symbol
}

data_weekly = hacer_request(params)

if data_weekly:
    df_weekly = convertir_a_dataframe(data_weekly, 'Weekly Time Series')
    df_weekly.columns = ['Open', 'High', 'Low', 'Close', 'Volume']

    print(f"✅ Datos semanales obtenidos")
    print(f"📅 Período: {df_weekly.index[-1].date()} a {df_weekly.index[0].date()}")
    print(f"📊 Total de semanas: {len(df_weekly)}")

    # Visualización
    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=df_weekly.index,
        y=df_weekly['Close'],
        mode='lines+markers',
        name='Precio de Cierre',
        line=dict(color='#F18F01', width=2)
    ))

    fig.update_layout(
        title=f'Precio Semanal - {symbol}',
        xaxis_title='Fecha',
        yaxis_title='Precio USD ($)',
        hovermode='x unified',
        template='plotly_white'
    )

    fig.show()
else:
    print("❌ No se pudieron obtener los datos semanales")

"""### 5.3 Time Series Mensual - Monthly Time Series"""

# ============================================
# 📆 TIME SERIES MENSUAL
# ============================================

print(f"📊 Obteniendo datos mensuales para {symbol}...")

params = {
    'function': 'TIME_SERIES_MONTHLY',
    'symbol': symbol
}

data_monthly = hacer_request(params)

if data_monthly:
    df_monthly = convertir_a_dataframe(data_monthly, 'Monthly Time Series')
    df_monthly.columns = ['Open', 'High', 'Low', 'Close', 'Volume']

    print(f"✅ Datos mensuales obtenidos")
    print(f"📅 Período: {df_monthly.index[-1].strftime('%Y-%m')} a {df_monthly.index[0].strftime('%Y-%m')}")
    print(f"📊 Total de meses: {len(df_monthly)}")

    # Crear gráfico interactivo con velas
    fig = make_subplots(rows=2, cols=1,
                        shared_xaxes=True,
                        vertical_spacing=0.03,
                        row_heights=[0.7, 0.3],
                        subplot_titles=('Precio Mensual', 'Volumen'))

    # Gráfico de velas
    fig.add_trace(go.Candlestick(
        x=df_monthly.index,
        open=df_monthly['Open'],
        high=df_monthly['High'],
        low=df_monthly['Low'],
        close=df_monthly['Close'],
        name='OHLC'
    ), row=1, col=1)

    # Volumen
    fig.add_trace(go.Bar(
        x=df_monthly.index,
        y=df_monthly['Volume'],
        name='Volumen',
        marker_color='#4ECDC4'
    ), row=2, col=1)

    fig.update_layout(
        title=f'Análisis Mensual - {symbol}',
        yaxis_title='Precio USD ($)',
        xaxis_title='Fecha',
        height=800,
        template='plotly_white'
    )

    fig.update_xaxes(rangeslider_visible=False, row=1, col=1)

    fig.show()

    # Calcular retorno mensual
    df_monthly['Return'] = df_monthly['Close'].pct_change() * 100
    print(f"\n📈 Retorno Mensual Promedio: {df_monthly['Return'].mean():.2f}%")
    print(f"📉 Volatilidad Mensual: {df_monthly['Return'].std():.2f}%")
else:
    print("❌ No se pudieron obtener los datos mensuales")

"""### 5.4 Time Series Intradiario - Intraday (5 minutos)"""

# ============================================
# ⏱️ TIME SERIES INTRADÍARIO (Requiere API Premium)
# ============================================
# Los datos intradía con `outputsize='full'` y la mayoría de los intervalos
# requieren una suscripción premium en Alpha Vantage.
# Para una cuenta gratuita, solo se admiten 5 solicitudes por minuto y
# los datos intradía suelen estar limitados a `outputsize='compact'` o
# no estar disponibles para algunos intervalos.
# Por lo tanto, esta sección está comentada.

# params = {
#     'function': 'TIME_SERIES_INTRADAY',
#     'symbol': symbol,
#     'interval': '5min',  # 1min, 5min, 15min, 30min, 60min
#     'outputsize': 'compact'  # últimos 100 puntos
# }

# data_intraday = hacer_request(params)

# if data_intraday:
#     df_intraday = convertir_a_dataframe(data_intraday, 'Time Series (5min)')
#     if df_intraday is not None:
#         df_intraday.columns = ['Open', 'High', 'Low', 'Close', 'Volume']

#         print(f"✅ Datos intradía obtenidos")
#         print(f" Último dato: {df_intraday.index[0]}")
#         print(f"📊 Total de puntos: {len(df_intraday)}")

#         # Visualización intradía
#         fig = go.Figure()

#         fig.add_trace(go.Scatter(
#             x=df_intraday.index,
#             y=df_intraday['Close'],
#             mode='lines',
#             name='Precio',
#             line=dict(color='#E63946', width=2)
#         ))

#         fig.update_layout(
#             title=f'Precio Intradía (5 min) - {symbol}',
#             xaxis_title='Hora',
#             yaxis_title='Precio USD ($)',
#             hovermode='x unified',
#             template='plotly_white',
#             xaxis=dict(
#                 rangeselector=dict(
#                     buttons=list([
#                         dict(count=1, label="1h", step="hour", stepmode="backward"),
#                         dict(count=2, label="2h", step="hour", stepmode="backward"),
#                         dict(step="all")
#                     ])
#                 ),
#                 rangeslider=dict(visible=True),
#                 type="date"
#             )
#         )

#         fig.show()
# else:
# print("❌ No se pudieron obtener los datos intradía o se requiere API Premium.")
# print("💡 Nota: Los datos intradía pueden requerir una API key premium")

# Asegurar que df_intraday esté definido como None si no se obtuvieron datos
df_intraday = None

"""## 6. Criptomonedas <a id='crypto'></a>

**⚠️ Nota sobre la API Gratuita:**

Los datos detallados de criptomonedas (`DIGITAL_CURRENCY_DAILY`) a menudo tienen limitaciones o pueden estar disponibles solo para las monedas principales con una API Key gratuita. Si encuentras errores o mensajes de 'Information' indicando que necesitas una suscripción premium, es probable que se deba a estas restricciones.

Por esta razón, la siguiente sección de código está comentada.
"""

# ============================================
# ₿ CRIPTOMONEDAS - DIGITAL CURRENCY (Limitado en API Gratuita)
# ============================================
# Datos históricos de criptomonedas
# Esta función puede estar limitada o requerir una API Key premium
# para algunas divisas o para obtener un historial completo.
# Por esta razón, la sección de código está comentada.

# crypto_symbol = 'BTC'  # Bitcoin
# market = 'USD'  # Mercado en dólares

# print(f" Obteniendo datos históricos de {crypto_symbol} en {market}...")

# params = {
#     'function': 'DIGITAL_CURRENCY_DAILY',
#     'symbol': crypto_symbol,
#     'market': market
# }

# data_crypto = hacer_request(params)

# if data_crypto:
#     df_crypto = convertir_a_dataframe(data_crypto, 'Time Series (Digital Currency Daily)')

#     if df_crypto is not None:
#         # Renombrar columnas específicas de crypto
#         # Los nombres originales de las columnas después de convertir a DF son '1. open', '2. high', etc.
#         df_crypto = df_crypto.rename(columns={
#             '1. open': 'Open',
#             '2. high': 'High',
#             '3. low': 'Low',
#             '4. close': 'Close',
#             '5. volume': 'Volume',
#             '6. market cap (USD)': 'Market Cap' # Esta columna sí tiene el (USD)
#         })

#         print(f"✅ Datos de {crypto_symbol} obtenidos")
#         print(f"📅 Período: {df_crypto.index[-1].date()} a {df_crypto.index[0].date()}")
#         print(f"📊 Total de registros: {len(df_crypto)}")

#         # Visualización
#         fig = make_subplots(rows=3, cols=1,
#                             shared_xaxes=True,
#                             vertical_spacing=0.05,
#                             subplot_titles=('Precio Bitcoin (BTC/USD)', 'Volumen', 'Market Cap'),
#                             row_heights=[0.5, 0.25, 0.25])

#         # Precio
#         fig.add_trace(go.Scatter(
#             x=df_crypto.index,
#             y=df_crypto['Close'],
#             mode='lines',
#             name='Precio',
#             line=dict(color='#F7931A', width=2)
#         ), row=1, col=1)

#         # Volumen
#         fig.add_trace(go.Bar(
#             x=df_crypto.index,
#             y=df_crypto['Volume'],
#             name='Volumen',
#             marker_color='#627EEA'
#         ), row=2, col=1)

#         # Market Cap
#         fig.add_trace(go.Scatter(
#             x=df_crypto.index,
#             y=df_crypto['Market Cap'],
#             mode='lines',
#             name='Market Cap',
#             line=dict(color='#26A17B', width=1)
#         ), row=3, col=1)

#         fig.update_layout(
#             title=f'Análisis de {crypto_symbol} ({market})',
#             height=900,
#             template='plotly_white',
#             showlegend=False
#         )

#         fig.update_yaxes(tickprefix='$', tickformat=',.0f', row=1, col=1)
#         fig.update_yaxes(tickprefix='$', tickformat=',.0f', row=3, col=1)

#         fig.show()

#         # Estadísticas
#         print(f"\n📊 Estadísticas de {crypto_symbol}:")
#         print(f"Precio Actual: ${df_crypto['Close'].iloc[0]:,.2f}")
#         print(f"Máximo Histórico: ${df_crypto['High'].max():,.2f}")
#         print(f"Mínimo del período: ${df_crypto['Low'].min():,.2f}")
#         print(f"Market Cap Actual: ${df_crypto['Market Cap'].iloc[0]:,.2f}")
#     else:
#         print("❌ No se pudieron procesar los datos de criptomonedas.")
# else:
#     print("❌ No se pudieron obtener los datos de criptomonedas")

df_crypto = None

"""## 7. Indicadores Técnicos <a id='tecnicos'></a>

### 7.1 SMA - Simple Moving Average

**⚠️ Nota sobre la API Gratuita:**

Aunque la Media Móvil Simple (SMA) es un indicador técnico fundamental, Alpha Vantage a menudo limita el acceso a ciertos indicadores técnicos o a la cantidad de datos históricos que se pueden obtener para ellos con una API Key gratuita. Es posible que el endpoint `SMA` devuelva un mensaje de 'Information' o que no se puedan obtener los datos completos.

Por esta razón, la siguiente sección de código está comentada.
"""

# ============================================
# 📊 SMA - SIMPLE MOVING AVERAGE (Limitado en API Gratuita)
# ============================================
# Los datos para este indicador pueden estar limitados o requerir una API Key premium.
# Por esta razón, la sección de código está comentada.

# symbol = 'IBM'
# time_period = 20  # días

# print(f"📊 Calculando SMA({time_period}) para {symbol}...")

# params = {
#     'function': 'SMA',
#     'symbol': symbol,
#     'interval': 'daily',
#     'time_period': time_period,
#     'series_type': 'close'
# }

# data_sma = hacer_request(params)

# if data_sma:
#     df_sma = convertir_a_dataframe(data_sma, 'Technical Analysis: SMA')
#     if df_sma is not None:
#         df_sma.columns = ['SMA']

#         print(f"✅ SMA calculada correctamente")

#         # Combinar con datos de precio
#         if df_stock is not None:
#             df_combined = pd.DataFrame({
#                 'Close': df_stock['Close'],
#                 'SMA': df_sma['SMA']
#             }).dropna()

#             # Visualización
#             fig = go.Figure()

#             fig.add_trace(go.Scatter(
#                 x=df_combined.index,
#                 y=df_combined['Close'],
#                 mode='lines',
#                 name='Precio',
#                 line=dict(color='#2E86AB', width=2)
#             ))

#             fig.add_trace(go.Scatter(
#                 x=df_combined.index,
#                 y=df_combined['SMA'],
#                 mode='lines',
#                 name=f'SMA ({time_period})',
#                 line=dict(color='#E63946', width=2, dash='dash')
#             ))

#             fig.update_layout(
#                 title=f'Precio vs SMA - {symbol}',
#                 xaxis_title='Fecha',
#                 yaxis_title='Precio USD ($)',
#                 hovermode='x unified',
#                 template='plotly_white'
#             )

#             fig.show()
#     else:
#         print("❌ No se pudieron procesar los datos del SMA.")
# else:
#     print("❌ No se pudo calcular el SMA o se requiere API Premium.")

df_sma = None

"""### 7.2 RSI - Relative Strength Index"""

# ============================================
#  RSI - RELATIVE STRENGTH INDEX
# ============================================
# Indicador de momentum (sobrecompra > 70, sobreventa < 30)

time_period = 14  # período estándar

print(f"💪 Calculando RSI({time_period}) para {symbol}...")

params = {
    'function': 'RSI',
    'symbol': symbol,
    'interval': 'daily',
    'time_period': time_period,
    'series_type': 'close'
}

data_rsi = hacer_request(params)

if data_rsi:
    df_rsi = convertir_a_dataframe(data_rsi, 'Technical Analysis: RSI')
    df_rsi.columns = ['RSI']

    print(f"✅ RSI calculado correctamente")
    print(f"📊 RSI Actual: {df_rsi['RSI'].iloc[0]:.2f}")

    # Interpretación
    current_rsi = df_rsi['RSI'].iloc[0]
    if current_rsi > 70:
        print("️ Señal: SOBRECOMPRA (posible corrección a la baja)")
    elif current_rsi < 30:
        print("️ Señal: SOBREVENTA (posible rebote al alza)")
    else:
        print("✅ Señal: NEUTRAL")

    # Visualización
    fig = make_subplots(rows=2, cols=1,
                        shared_xaxes=True,
                        vertical_spacing=0.05,
                        row_heights=[0.6, 0.4])

    # Precio
    fig.add_trace(go.Scatter(
        x=df_stock.index,
        y=df_stock['Close'],
        mode='lines',
        name='Precio',
        line=dict(color='#2E86AB', width=2)
    ), row=1, col=1)

    # RSI
    fig.add_trace(go.Scatter(
        x=df_rsi.index,
        y=df_rsi['RSI'],
        mode='lines',
        name='RSI',
        line=dict(color='#E63946', width=2)
    ), row=2, col=1)

    # Líneas de sobrecompra/sobreventa
    fig.add_hline(y=70, line_dash="dash", line_color="red", annotation_text="Sobrecompra", row=2, col=1)
    fig.add_hline(y=30, line_dash="dash", line_color="green", annotation_text="Sobreventa", row=2, col=1)

    fig.update_layout(
        title=f'Análisis Técnico - {symbol} con RSI',
        height=700,
        template='plotly_white',
        showlegend=True
    )

    fig.update_yaxes(range=[0, 100], row=2, col=1)

    fig.show()
else:
    print("❌ No se pudo calcular el RSI")

"""### 7.3 MACD - Moving Average Convergence Divergence

**⚠️ Nota sobre la API Gratuita:**

El indicador MACD (Moving Average Convergence Divergence), aunque es un indicador técnico estándar, a menudo forma parte de los endpoints premium de Alpha Vantage o tiene limitaciones significativas en su uso con una API Key gratuita. Esto significa que la solicitud podría fallar o devolver datos incompletos.

Por lo tanto, la siguiente sección de código está comentada.
"""

# ============================================
# 📈 MACD - MOVING AVERAGE CONVERGENCE DIVERGENCE (Requiere API Premium)
# ============================================
# El indicador MACD, aunque es un indicador técnico estándar, a menudo
# forma parte de los endpoints premium o tiene limitaciones en su uso
# con una API key gratuita. Por lo tanto, esta sección está comentada.

print(f" Calculando MACD para {symbol} (esta función requiere API Premium)...")

# params = {
#     'function': 'MACD',
#     'symbol': symbol,
#     'interval': 'daily',
#     'series_type': 'close',
#     'fastperiod': 12,
#     'slowperiod': 26,
#     'signalperiod': 9
# }

# data_macd = hacer_request(params)

# if data_macd:
#     df_macd = convertir_a_dataframe(data_macd, 'Technical Analysis: MACD')
#     if df_macd is not None:
#         print(f"✅ MACD calculado correctamente")

#         # Visualización
#         fig = make_subplots(rows=2, cols=1,
#                             shared_xaxes=True,
#                             vertical_spacing=0.05,
#                             row_heights=[0.6, 0.4])

#         # Precio
#         fig.add_trace(go.Scatter(
#             x=df_stock.index,
#             y=df_stock['Close'],
#             mode='lines',
#             name='Precio',
#             line=dict(color='#2E86AB', width=2)
#         ), row=1, col=1)

#         # MACD
#         fig.add_trace(go.Scatter(
#             x=df_macd.index,
#             y=df_macd['MACD'],
#             mode='lines',
#             name='MACD',
#             line=dict(color='#F18F01', width=2)
#         ), row=2, col=1)

#         # Signal
#         fig.add_trace(go.Scatter(
#             x=df_macd.index,
#             y=df_macd['MACD_Signal'],
#             mode='lines',
#             name='Signal',
#             line=dict(color='#E63946', width=2, dash='dash')
#         ), row=2, col=1)

#         # Histograma
#         fig.add_trace(go.Bar(
#             x=df_macd.index,
#             y=df_macd['MACD_Hist'],
#             name='Histograma',
#             marker_color=np.where(df_macd['MACD_Hist'] > 0, '#26A17B', '#E63946')
#         ), row=2, col=1)

#         fig.update_layout(
#             title=f'Análisis MACD - {symbol}',
#             height=700,
#             template='plotly_white',
#             showlegend=True
#         )

#         fig.show()

#         # Señal actual
#         macd_val = df_macd['MACD'].iloc[0]
#         signal_val = df_macd['MACD_Signal'].iloc[0]

#         if macd_val > signal_val:
#             print("📊 Señal: ALCISTA (MACD por encima de Signal)")
#         else:
#             print(" Señal: BAJISTA (MACD por debajo de Signal)")
#     else:
#         print("❌ No se pudieron procesar los datos de MACD.")
# else:
print("❌ No se pudo calcular el MACD o se requiere API Premium.")

df_macd = None

"""### 7.4 Bollinger Bands"""

# ============================================
# 📊 BOLLINGER BANDS
# ============================================

print(f" Calculando Bandas de Bollinger para {symbol}...")

params = {
    'function': 'BBANDS',
    'symbol': symbol,
    'interval': 'daily',
    'time_period': 20,
    'series_type': 'close',
    'nbdevup': 2,
    'nbdevdn': 2
}

data_bbands = hacer_request(params)

if data_bbands:
    df_bbands = convertir_a_dataframe(data_bbands, 'Technical Analysis: BBANDS')

    if df_bbands is not None:
        print(f"✅ Bandas de Bollinger calculadas")

        # Combinar con datos de precio, asegurando que los índices coincidan
        # Usamos merge para alinear correctamente los DataFrames por fecha.
        # Solo tomamos las columnas necesarias y hacemos un 'inner' join para fechas comunes.
        df_combined_bb = pd.merge(df_stock[['Close']], df_bbands, left_index=True, right_index=True, how='inner')

        # Visualización
        fig = go.Figure()

        # Precio de cierre
        fig.add_trace(go.Scatter(
            x=df_combined_bb.index,
            y=df_combined_bb['Close'],
            mode='lines',
            name='Precio',
            line=dict(color='#2E86AB', width=2)
        ))

        # Banda superior
        fig.add_trace(go.Scatter(
            x=df_combined_bb.index,
            y=df_combined_bb['Real Upper Band'],
            mode='lines',
            name='Banda Superior',
            line=dict(color='#E63946', width=1, dash='dash'),
            fill=None
        ))

        # Banda media
        fig.add_trace(go.Scatter(
            x=df_combined_bb.index,
            y=df_combined_bb['Real Middle Band'],
            mode='lines',
            name='Banda Media',
            line=dict(color='#F18F01', width=2)
        ))

        # Banda inferior
        fig.add_trace(go.Scatter(
            x=df_combined_bb.index,
            y=df_combined_bb['Real Lower Band'],
            mode='lines',
            name='Banda Inferior',
            line=dict(color='#26A17B', width=1, dash='dash'),
            fill='tonexty'
        ))

        fig.update_layout(
            title=f'Bandas de Bollinger - {symbol}',
            xaxis_title='Fecha',
            yaxis_title='Precio USD ($)',
            hovermode='x unified',
            template='plotly_white',
            height=600
        )

        fig.show()

        # Análisis actual
        # Asegurarse de usar df_combined_bb para el análisis actual
        if not df_combined_bb.empty:
            current_price = df_combined_bb['Close'].iloc[0]
            upper = df_combined_bb['Real Upper Band'].iloc[0]
            lower = df_combined_bb['Real Lower Band'].iloc[0]

            if current_price > upper:
                print("⚠️ Precio por encima de la banda superior (posible sobrecompra)")
            elif current_price < lower:
                print("⚠️ Precio por debajo de la banda inferior (posible sobreventa)")
            else:
                print("✅ Precio dentro de las bandas de Bollinger")
        else:
            print("⚠️ No hay datos suficientes para el análisis actual de Bandas de Bollinger.")
    else:
        print("❌ No se pudieron procesar los datos de Bandas de Bollinger.")
else:
    print("❌ No se pudieron calcular las Bandas de Bollinger")

"""## 8. Commodities <a id='commodities'></a>

### 8.1 Oro y Plata
"""

# ============================================
# 🥇 ORO - GOLD PRICES
# ============================================

print(" Obteniendo precios históricos del Oro...")

params = {
    'function': 'GOLD_SILVER_HISTORY',
    'symbol': 'GOLD',
    'interval': 'daily'
}

data_gold = hacer_request(params)

if data_gold:
    df_gold = convertir_commodities_a_dataframe(data_gold)
    # La columna ya se llama 'value' o 'Price' según la API, ajustamos si es necesario.
    # Si la API devuelve 'value', la renombramos a 'Price'
    if df_gold is not None:
        if 'value' in df_gold.columns: # Alpha Vantage puede devolver 'value' o 'price' para commodities
            df_gold = df_gold.rename(columns={'value': 'Price'})
        elif 'open' in df_gold.columns: # Si devuelve open, high, low, close
             df_gold = df_gold.rename(columns={'open': 'Open', 'high': 'High', 'low': 'Low', 'close': 'Close'})
        else:
            print("⚠️ Columna de precio no reconocida en datos de Oro. Usando la primera columna disponible como 'Price'.")
            df_gold.columns = ['Price'] + list(df_gold.columns[1:])


        print(f"✅ Precios del oro obtenidos")
        print(f"📅 Período: {df_gold.index[-1].date()} a {df_gold.index[0].date()}")
        print(f"💰 Precio Actual: ${df_gold['Price'].iloc[0]:.2f}")

        # Visualización
        fig = go.Figure()

        fig.add_trace(go.Scatter(
            x=df_gold.index,
            y=df_gold['Price'],
            mode='lines',
            name='Oro',
            line=dict(color='#FFD700', width=2)
        ))

        fig.update_layout(
            title='Precio del Oro (USD/oz)',
            xaxis_title='Fecha',
            yaxis_title='Precio USD ($)',
            hovermode='x unified',
            template='plotly_white',
            height=500
        )

        fig.show()
    else:
        print("❌ No se pudieron procesar los datos del oro.")
else:
    print("❌ No se pudieron obtener los datos del oro")

# ============================================
# 🥈 PLATA - SILVER PRICES
# ============================================

print("🥈 Obteniendo precios históricos de la Plata...")

params = {
    'function': 'GOLD_SILVER_HISTORY',
    'symbol': 'SILVER',
    'interval': 'daily'
}

data_silver = hacer_request(params)

if data_silver:
    df_silver = convertir_commodities_a_dataframe(data_silver)

    if df_silver is not None:
        if 'value' in df_silver.columns:
            df_silver = df_silver.rename(columns={'value': 'Price'})
        elif 'open' in df_silver.columns:
             df_silver = df_silver.rename(columns={'open': 'Open', 'high': 'High', 'low': 'Low', 'close': 'Close'})
        else:
            print("⚠️ Columna de precio no reconocida en datos de Plata. Usando la primera columna disponible como 'Price'.")
            df_silver.columns = ['Price'] + list(df_silver.columns[1:])

        print(f"✅ Precios de la plata obtenidos")
        print(f" Precio Actual: ${df_silver['Price'].iloc[0]:.2f}")

        # Comparación Oro vs Plata
        if 'df_gold' in locals() and df_gold is not None:
            fig = make_subplots(rows=2, cols=1,
                                shared_xaxes=True,
                                subplot_titles=('Oro', 'Plata'))

            fig.add_trace(go.Scatter(
                x=df_gold.index,
                y=df_gold['Price'],
                mode='lines',
                name='Oro',
                line=dict(color='#FFD700', width=2)
            ), row=1, col=1)

            fig.add_trace(go.Scatter(
                x=df_silver.index,
                y=df_silver['Price'],
                mode='lines',
                name='Plata',
                line=dict(color='#C0C0C0', width=2)
            ), row=2, col=1)

            fig.update_layout(
                title='Comparación: Oro vs Plata',
                height=700,
                template='plotly_white'
            )

            fig.show()

            # Ratio Oro/Plata (asegurarse de que los índices estén alineados)
            # Usar pd.merge para combinar y luego calcular el ratio
            if not df_gold.empty and not df_silver.empty:
                df_gold_silver = pd.merge(df_gold[['Price']], df_silver[['Price']], left_index=True, right_index=True, how='inner', suffixes=('_gold', '_silver'))
                if not df_gold_silver.empty:
                    ratio = df_gold_silver['Price_gold'] / df_gold_silver['Price_silver']
                    print(f"\n📊 Ratio Oro/Plata Actual: {ratio.iloc[0]:.2f}")
                else:
                    print("⚠️ No hay fechas comunes para calcular el Ratio Oro/Plata.")
            else:
                print("⚠️ No hay datos suficientes de Oro o Plata para calcular el Ratio.")
        else:
            print("⚠️ No hay datos de Oro disponibles para comparar.")
    else:
        print("❌ No se pudieron procesar los datos de la plata.")
else:
    print("❌ No se pudieron obtener los datos de la plata")

"""### 8.2 Petróleo - WTI"""

# ============================================
# 🛢️ PETRÓLEO - WTI CRUDE OIL
# ============================================

print("🛢️ Obteniendo precios del petróleo WTI...")

params = {
    'function': 'WTI',
    'interval': 'daily'
}

data_wti = hacer_request(params)

if data_wti:
    df_wti = convertir_commodities_a_dataframe(data_wti)

    if df_wti is not None:
        # La columna para WTI suele ser 'value'
        if 'value' in df_wti.columns:
            df_wti = df_wti.rename(columns={'value': 'Price'})
        else:
            print("⚠️ Columna de precio no reconocida en datos de WTI. Usando la primera columna disponible como 'Price'.")
            df_wti.columns = ['Price'] + list(df_wti.columns[1:])

        print(f"✅ Precios del WTI obtenidos")
        print(f"💰 Precio Actual: ${df_wti['Price'].iloc[0]:.2f}")

        # Visualización
        fig = go.Figure()

        fig.add_trace(go.Scatter(
            x=df_wti.index,
            y=df_wti['Price'],
            mode='lines+markers',
            name='WTI',
            line=dict(color='#2E86AB', width=2),
            marker=dict(size=4)
        ))

        fig.update_layout(
            title='Precio del Petróleo WTI (USD/barril)',
            xaxis_title='Fecha',
            yaxis_title='Precio USD ($)',
            hovermode='x unified',
            template='plotly_white',
            height=500
        )

        fig.show()
    else:
        print("❌ No se pudieron procesar los datos del petróleo WTI.")
else:
    print("❌ No se pudieron obtener los datos del petróleo WTI")

"""## 9. Análisis Comparativo y Dashboard Final"""

# ============================================
#  DASHBOARD COMPARATIVO
# ============================================
# Comparar múltiples activos

print("📊 Creando dashboard comparativo...")

# Crear DataFrame comparativo con retornos
comparativo = pd.DataFrame()

if df_stock is not None:
    comparativo['IBM'] = df_stock['Close'].pct_change() * 100

if 'df_crypto' in locals() and df_crypto is not None and 'Close' in df_crypto.columns:
    comparativo['BTC'] = df_crypto['Close'].pct_change() * 100

if 'df_gold' in locals() and df_gold is not None and 'Price' in df_gold.columns:
    comparativo['Oro'] = df_gold['Price'].pct_change() * 100

if 'df_wti' in locals() and df_wti is not None and 'Price' in df_wti.columns:
    comparativo['WTI'] = df_wti['Price'].pct_change() * 100

comparativo = comparativo.dropna()

if not comparativo.empty:
    # Gráfico de correlación
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))

    # Heatmap de correlación
    corr_matrix = comparativo.corr()
    sns.heatmap(corr_matrix, annot=True, cmap='RdYlGn', center=0,
                fmt='.2f', linewidths=0.5, ax=axes[0])
    axes[0].set_title('Matriz de Correlación de Retornos', fontsize=14, fontweight='bold')

    # Distribución de retornos
    for col in comparativo.columns:
        sns.kdeplot(data=comparativo[col], label=col, ax=axes[1])
    axes[1].set_title('Distribución de Retornos Diarios', fontsize=14, fontweight='bold')
    axes[1].set_xlabel('Retorno (%)')
    axes[1].legend()

    plt.tight_layout()
    plt.show()

    # Estadísticas
    print("\n📊 RESUMEN ESTADÍSTICO:")
    print("="*60)
    stats = pd.DataFrame({
        'Retorno Promedio (%)': comparativo.mean() * 100,
        'Volatilidad (%)': comparativo.std() * 100,
        'Máximo (%)': comparativo.max() * 100,
        'Mínimo (%)': comparativo.min() * 100
    })
    display(stats.round(2))
else:
    print("⚠️ No hay suficientes datos para el análisis comparativo")

# ============================================
#  ANÁLISIS DE RENDIMIENTO ACUMULADO
# ============================================

if not comparativo.empty:
    # Calcular rendimiento acumulado
    rendimiento_acumulado = (1 + comparativo/100).cumprod() - 1

    fig = go.Figure()

    for col in rendimiento_acumulado.columns:
        fig.add_trace(go.Scatter(
            x=rendimiento_acumulado.index,
            y=rendimiento_acumulado[col],
            mode='lines',
            name=col,
            line=dict(width=2)
        ))

    fig.update_layout(
        title='Rendimiento Acumulado Comparativo',
        xaxis_title='Fecha',
        yaxis_title='Rendimiento Acumulado',
        hovermode='x unified',
        template='plotly_white',
        height=600,
        yaxis=dict(tickformat='.0%')
    )

    fig.show()

"""## 10. Resumen y Conclusiones"""

# ============================================
# 📝 RESUMEN FINAL
# ============================================

print("\n" + "="*70)
print(" "*20 + " RESUMEN DEL ANÁLISIS ")
print("="*70)

print("\n✅ FUNCIONALIDADES EXPLORADAS:")
print("-" * 70)
print("1. ✓ Time Series Diario, Semanal y Mensual")
print("2. ✓ Indicadores Técnicos:")
print("   • RSI (Relative Strength Index)")
print("   • Bandas de Bollinger")
print("3. ✓ Commodities (Oro, Plata, Petróleo WTI)")
print("4. ✓ Visualizaciones Interactivas con Plotly")
print("5. ✓ Análisis Comparativo y Correlaciones")

print("\n❌ FUNCIONALIDADES NO EXPLORADAS (API Premium / Limitaciones):")
print("-" * 70)
print("• Time Series Intradía")
print("• Datos de Criptomonedas")
print("• SMA (Simple Moving Average)")
print("• MACD (Moving Average Convergence Divergence)")

print("\n📊 DATOS OBTENIDOS:")
print("-" * 70)

if df_stock is not None:
    print(f"• Acciones (IBM): {len(df_stock)} registros")
# if 'df_crypto' in locals() and df_crypto is not None:
#     print(f"• Bitcoin: {len(df_crypto)} registros")
if 'df_gold' in locals() and df_gold is not None:
    print(f"• Oro: {len(df_gold)} registros")
if 'df_wti' in locals() and df_wti is not None:
    print(f"• Petróleo WTI: {len(df_wti)} registros")

print("\n💡 RECOMENDACIONES:")
print("-" * 70)
print("• Para datos intradía, criptomonedas, o indicadores técnicos avanzados, considera una API premium")
print("• El límite gratuito es de 5 requests por minuto")
print("• Usa outputsize='full' solo si necesitas datos históricos completos")
print("• Combina múltiples indicadores para mejores señales de trading")

print("\n" + "="*70)
print(" "*25 + "¡Análisis Completado!")
print("="*70)

"""## 🎓 Recursos Adicionales

**Documentación Oficial:**
- Alpha Vantage API: https://www.alphavantage.co/documentation/
- Obtener API Key: https://www.alphavantage.co/support/#api-key

**Librerías Utilizadas:**
- Pandas: Manipulación de datos
- Matplotlib/Seaborn: Visualizaciones estáticas
- Plotly: Visualizaciones interactivas
- Requests: Conexión con API

**Indicadores Técnicos:**
- SMA: Tendencia a largo plazo
- RSI: Momentum (sobrecompra > 70, sobreventa < 30)
- MACD: Cruce de tendencias
- Bollinger: Volatilidad del mercado

---

### ⚠️ Disclaimer
Este cuaderno es solo con fines educativos. No constituye asesoramiento financiero. Siempre realiza tu propia investigación antes de tomar decisiones de inversión.
"""